// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/snowmarket-vibes/AlpineLodge.tsx": () => import("../components/mockups/snowmarket-vibes/AlpineLodge.tsx"),
  "./components/mockups/snowmarket-vibes/MidnightPro.tsx": () => import("../components/mockups/snowmarket-vibes/MidnightPro.tsx"),
  "./components/mockups/snowmarket-vibes/PowderDay.tsx": () => import("../components/mockups/snowmarket-vibes/PowderDay.tsx")
};
